"""empty message

Revision ID: 790aca5ee2c1
Revises: 
Create Date: 2018-08-04 14:17:16.040706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790aca5ee2c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_barang',
    sa.Column('kode', sa.String(length=6), nullable=False),
    sa.Column('nama', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('pegawai',
    sa.Column('kode', sa.String(length=6), nullable=False),
    sa.Column('nama', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('barang',
    sa.Column('kode', sa.String(length=13), nullable=False),
    sa.Column('nama', sa.String(length=128), nullable=False),
    sa.Column('jenis_barang', sa.String(length=6), nullable=False),
    sa.Column('satuan', sa.String(length=32), nullable=True),
    sa.Column('harga_beli', sa.Integer(), nullable=False),
    sa.Column('harga_jual', sa.Integer(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jenis_barang'], ['jenis_barang.kode'], ),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('penjualan',
    sa.Column('nota', sa.String(length=15), nullable=False),
    sa.Column('kasir', sa.String(length=6), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kasir'], ['pegawai.kode'], ),
    sa.PrimaryKeyConstraint('nota')
    )
    op.create_table('detail_penjualan',
    sa.Column('item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota', sa.String(length=15), nullable=False),
    sa.Column('barang', sa.String(length=13), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barang'], ['barang.kode'], ),
    sa.ForeignKeyConstraint(['nota'], ['penjualan.nota'], ),
    sa.PrimaryKeyConstraint('item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_penjualan')
    op.drop_table('penjualan')
    op.drop_table('barang')
    op.drop_table('pegawai')
    op.drop_table('jenis_barang')
    # ### end Alembic commands ###
